---
- name: install tools 
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - ethtool
    - ebtables
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common
