---
- name: disable swap
  shell: swapoff -a

- name: comment out swap in /etc/fstab
  replace:
   path: /etc/fstab
   regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
   replace: '# \1'

- name: configure iptables to receive bridged network traffic
  blockinfile:
    path: /etc/ufw/sysctl.conf
    block: |
      net/bridge/bridge-nf-call-ip6tables = 1
      net/bridge/bridge-nf-call-iptables = 1
      net/bridge/bridge-nf-call-arptables = 1
